// Generated by CoffeeScript 1.3.3
(function() {
  var Politix, cheerio, data, request, util;

  request = require('request');

  cheerio = require('cheerio');

  util = require('util');

  Politix = (function() {

    function Politix() {
      this.name = 'Politix';
      this.domain = 'http://politix.topix.com';
      this.done = 0;
    }

    Politix.prototype.get_data = function() {
      var author, url, _i, _len, _ref, _results;
      _ref = ['politixmayday', 'politixdain', 'politixmary', 'politixdavid'];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        author = _ref[_i];
        url = "" + this.domain + "/profile/" + author;
        _results.push(this.scrape(author, url));
      }
      return _results;
    };

    Politix.prototype.scrape = function(author, url) {
      var callback,
        _this = this;
      callback = function(error, response, body) {
        var $, $article, article, articles, comments, span, timestamp, title, _i, _len, _ref;
        $ = cheerio.load(body);
        articles = $('article');
        for (_i = 0, _len = articles.length; _i < _len; _i++) {
          article = articles[_i];
          $article = $(article);
          title = $article.find('div.bd a h3').text();
          _ref = (function() {
            var _j, _len1, _ref, _results;
            _ref = $article.find('div.bd p.margint5 span');
            _results = [];
            for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
              span = _ref[_j];
              _results.push(span.next.data);
            }
            return _results;
          })(), timestamp = _ref[0], comments = _ref[1];
          data.push({
            'author': author,
            'title': title,
            'timestamp': timestamp,
            'comments': comments
          });
        }
        _this.done++;
        if (_this.done === 4) {
          util.puts(JSON.stringify(data, null, 2));
          return process.exit(0);
        }
      };
      return request({
        uri: url
      }, callback);
    };

    return Politix;

  })();

  data = [];

  (new Politix).get_data();

}).call(this);
